### ISSUE TITLE
Please document skynet protocol API

### ISSUE THREAD

**Issue by MineRobber9000** [osmarks/skynet#1]
I was wondering what kind of tracking goes into a program like this (read: what goes into it on the protocol side) and also was wondering how to possibly program a web client (a nicer skinned version of the log viewer) for a program of mine.

**Comment by osmarks** [comment]
I'm not certain what you mean by "what kind of tracking" but I'll go document the protocol now.

**Comment by osmarks** [comment]
Done. Please tell me if there are any problems with it.

**Comment by MineRobber9000** [comment]
The docs are good.
