### ISSUE TITLE
Version compatibility?

### ISSUE THREAD

**Issue by JWBstuhr** [osmarks/skynet#10]
Which versions of ComputerCraft does this work with? I'm asking because I'm running CC: Tweaked 1.12.2 v1.89.2, and it keeps failing websocket connections, so I'd like to know what versions of Minecraft and CC: Tweaked I need to use.

**Comment by osmarks** [comment]
It should work on any version of CC: Tweaked, as they all have websocket support. As far as I can tell the server has been up fine (https://status.osmarks.net/) so it probably isn't that. There has been another issue (#3) regarding this, but I can't reproduce it unfortunately. If you can try fiddling around with the socket on a computer ingame and see exactly what operation doesn't work that would be helpful.

**Comment by JWBstuhr** [comment]
I'm not sure what you mean by fiddling with the socket. I did try http.websocket, though.
`http.websocket("wss://skynet.osmarks.net/connect/")`
and it returns false, "Could not connect."

**Comment by osmarks** [comment]
Strange. I assumed it would be with writing or reading it. What if you try a HTTP request (via `wget` to https://skynet.osmarks.net/)?

**Comment by JWBstuhr** [comment]
It returns a failure as well.
`Connecting to https://skynet.osmarks.net/...`
`Failed.`

**Comment by osmarks** [comment]
Unfortunately, I have no idea what could be causing this without logs. Do you have logs saying anything about what happens?

**Comment by JWBstuhr** [comment]
Logs?

**Comment by osmarks** [comment]
The Minecraft logs. I assume if there was an issue CC might write stuff to those.

**Comment by JWBstuhr** [comment]
I don't think it's a version problem, all of my Minecraft versions, 1.12.2, 1.14.4, and 1.16.4 don't work
I tried 3 separate versions of CC: Tweaked, and nothing.

**Comment by osmarks** [comment]
I guess it's probably some sort of weird OS-level issue. Possibly something with CAs, but I doubt it as LetsEncrypt should be pretty universally supported by now.

**Comment by JWBstuhr** [comment]
Strangely it works on an Aternos server.. must be something on my end, then
