### ISSUE TITLE
Server unavailable 

### ISSUE THREAD

**Issue by Crayder** [osmarks/skynet#3]
"Skynet server unavailable, broken or running newer protocol version."

`Minecraft`: 1.16.4
`Computercraft`: CC: Tweaked 1.94.0
`Modpack`: Valhelsia 3.1.0

Latest download from master branch. Any ideas? Tested your socket on a testing platform and it connects fine, but not within my lua scripts.

**Comment by osmarks** [comment]
The server seems to be working fine still, so perhaps your server/world is blocking outbound HTTP connections, or there were some incompatible changes to websockets in newer CC:Tweaked than I tested on.

**Comment by Crayder** [comment]
Weird, it does the same thing for me locally as well on a singleplayer world. Not sure how to further narrow it down.
